# Generated by Django 5.1.5 on 2025-04-11 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiotweet',
            old_name='created_at',
            new_name='uploaded_at',
        ),
    ]
